# Generated by Django 5.1.1 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionesNota',
            fields=[
                ('versiones_nota_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=75)),
                ('fecha_version', models.DateTimeField()),
            ],
            options={
                'db_table': 'versiones_nota',
                'managed': False,
            },
        ),
    ]
