# Generated by Django 5.1.1 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompartirNotas',
            fields=[
                ('compartir_notas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permiso', models.BooleanField()),
                ('fecha_compartido', models.DateTimeField()),
            ],
            options={
                'db_table': 'compartir_notas',
                'managed': False,
            },
        ),
    ]
