# Generated by Django 5.1.1 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('notas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90)),
                ('contenido', models.TextField(null=True)),
                ('img_url', models.CharField(max_length=120, null=True)),
                ('es_favorita', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notas',
                'managed': False,
            },
        ),
    ]
