# Generated by Django 5.1.1 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentosCodigo',
            fields=[
                ('fragmentos_codigo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido_codigo', models.TextField()),
                ('lenguaje', models.CharField(max_length=40)),
                ('orden_en_nota', models.IntegerField()),
            ],
            options={
                'db_table': 'fragmentos_codigo',
                'managed': False,
            },
        ),
    ]
