# Generated by Django 5.1.1 on 2024-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarios_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=120)),
                ('pista_password', models.CharField(max_length=80)),
                ('activo', models.BooleanField(null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('ultimo_acceso', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
