# Generated by Django 5.1.1 on 2024-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuarios_pista_password_usuarios_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pista_password',
            field=models.CharField(default='default_password_hint', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
