# Generated by Django 5.1.1 on 2024-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('etiquetas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'etiquetas',
                'managed': False,
            },
        ),
    ]
